// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using jwtcore.Data;

namespace jwtcore.Migrations
{
    [DbContext(typeof(AdvisorContext))]
    [Migration("20210817021515_InitialMigrations")]
    partial class InitialMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("jwtcore.Models.Advisor", b =>
                {
                    b.Property<int>("AdvisorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("AdvisorId");

                    b.ToTable("Advisors");
                });

            modelBuilder.Entity("jwtcore.Models.Authentication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Authentications");
                });

            modelBuilder.Entity("jwtcore.Models.Faculty", b =>
                {
                    b.Property<int>("FacultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FacultyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FacultyDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FacultyId");

                    b.ToTable("Faculty");
                });

            modelBuilder.Entity("jwtcore.Models.Level", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("LevelCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LevelDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProgrammeProgramId")
                        .HasColumnType("int");

                    b.HasKey("LevelId");

                    b.HasIndex("ProgrammeProgramId");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("jwtcore.Models.Programme", b =>
                {
                    b.Property<int>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AdvisorId")
                        .HasColumnType("int");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("ProgramCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProgramDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudentUwiId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProgramId");

                    b.HasIndex("AdvisorId");

                    b.HasIndex("FacultyId");

                    b.ToTable("Programmes");
                });

            modelBuilder.Entity("jwtcore.Models.Specialization", b =>
                {
                    b.Property<int>("SpecializationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("MajCode")
                        .HasColumnType("text");

                    b.Property<string>("MajDesc")
                        .HasColumnType("text");

                    b.Property<int?>("ProgrammeProgramId")
                        .HasColumnType("int");

                    b.Property<string>("StudentUwiId")
                        .HasColumnType("text");

                    b.HasKey("SpecializationId");

                    b.HasIndex("ProgrammeProgramId");

                    b.ToTable("Specializations");
                });

            modelBuilder.Entity("jwtcore.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AdvisorId")
                        .HasColumnType("int");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProgrammeProgramId")
                        .HasColumnType("int");

                    b.Property<string>("StudentUwiId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StudentId");

                    b.HasIndex("AdvisorId");

                    b.HasIndex("ProgrammeProgramId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("jwtcore.Models.Level", b =>
                {
                    b.HasOne("jwtcore.Models.Programme", null)
                        .WithMany("Levels")
                        .HasForeignKey("ProgrammeProgramId");
                });

            modelBuilder.Entity("jwtcore.Models.Programme", b =>
                {
                    b.HasOne("jwtcore.Models.Advisor", null)
                        .WithMany("Programmes")
                        .HasForeignKey("AdvisorId");

                    b.HasOne("jwtcore.Models.Faculty", "faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId");
                });

            modelBuilder.Entity("jwtcore.Models.Specialization", b =>
                {
                    b.HasOne("jwtcore.Models.Programme", null)
                        .WithMany("Specializations")
                        .HasForeignKey("ProgrammeProgramId");
                });

            modelBuilder.Entity("jwtcore.Models.Student", b =>
                {
                    b.HasOne("jwtcore.Models.Advisor", null)
                        .WithMany("Students")
                        .HasForeignKey("AdvisorId");

                    b.HasOne("jwtcore.Models.Programme", "Programme")
                        .WithMany()
                        .HasForeignKey("ProgrammeProgramId");
                });
#pragma warning restore 612, 618
        }
    }
}
